[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FBB117"  # Yellow background color
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"  # Black text color
font = "sans serif"

[sidebar]
collapsed = true

[deprecation]
showPyplotGlobalUse = false
